### ISSUE TITLE
task任务投递

### ISSUE THREAD

**Issue by tigth** [xavieryang007/think-swoole-demo#2]
前辈，task任务投递和接收怎么搞啊

**Comment by xavieryang007** [comment]
都把我叫老了!

![image](https://user-images.githubusercontent.com/6174650/71161968-4dd4ae00-2285-11ea-9730-f48ff336c876.png)


目前里边通过事件触发的，不能直接投递闭包等任务

**Comment by tigth** [comment]
onTask的方法写在哪呢，任务投递了，接收任务的代码不知在哪写，不可能直接改他的源码ontask吧
![image](https://user-images.githubusercontent.com/49049400/71222296-faa53e80-230a-11ea-8d85-0a1cc4f63dbd.png)

**Comment by xavieryang007** [comment]
已经更新文档，可以查看最新文档
