### ISSUE TITLE
Class rpc\contract\Test\DemoInterface does not exist

### ISSUE THREAD

**Issue by k713927** [xavieryang007/think-swoole-demo#4]
Class rpc\contract\Test\DemoInterface does not exist

启动项目之后，访问/testrpc 路径，出现这样的提示，发现rpc.php在app目录下是存在的，tp的trace里面发现并没有加载，所以出现这个命名空间不存在，怎么办😰

**Comment by xavieryang007** [comment]
贴出来你的目录结构，你一个错误信息，无法定位你的具体原因。错误的字面含义已经很清楚了

**Comment by haifengZ** [comment]
> 贴出来你的目录结构，你一个错误信息，无法定位你的具体原因。错误的字面含义已经很清楚了
 
 DemoInterface 是接口 ，不应该是implements后才能使用吗，还是我书读的少了 !^_^

**Comment by xavieryang007** [comment]
注入的参数是接口，但是容器绑定的时候会将接口的名称作为参数，接口的实现类作为value保存。
