### ISSUE TITLE
Swoole\Client::connect(): connect to server[127.0.0.1:8081] failed, Error: Operation now in progress[36] 

### ISSUE THREAD

**Issue by skboy** [xavieryang007/think-swoole-demo#6]
按照你的配置配好后 
客户端 输入 php think rpc:interface 抱这个错
Swoole\Client::connect(): connect to server[127.0.0.1:9001] failed, Error: Operation now in progress[36] 
这是啥问题呀,可以解答一下嘛

**Comment by xavieryang007** [comment]
我代码没有出现这个问题，所以要想分析你的问题，你要贴出来的你的步骤和代码
