### ISSUE TITLE
tp和swoft互联rpc教程,希望大神能过目一下

### ISSUE THREAD

**Issue by nanyounanyounan** [xavieryang007/think-swoole-demo#7]
我弄这个的目的是想让更多的人使用tp-swoole,并没有其他挑衅的意思
**thinkphp-swoole3.0 调用swoft的微服务**
`
private function sendToSwoftRpc($host, $class, $method, $param, $version = '1.0', $ext = []) {
    $fp = stream_socket_client($host, $errno, $errstr);
    if (!$fp) {
        throw new Exception("stream_socket_client fail errno={$errno} errstr={$errstr}");
    }

    $req = [
        "jsonrpc" => '2.0',
        "method" => sprintf("%s::%s::%s", $version, $class, $method),
        'params' => $param,
        'id' => '',
        'ext' => $ext,
    ];
    $data = json_encode($req) . "\r\n\r\n";
    fwrite($fp, $data);

    $result = '';
    while (!feof($fp)) {
        $tmp = stream_socket_recvfrom($fp, 1024);

        if ($pos = strpos($tmp, "\r\n\r\n")) {
            $result .= substr($tmp, 0, $pos);
            break;
        } else {
            $result .= $tmp;
        }
    }

    fclose($fp);
    return json_decode($result, true);
}
//调用
$ret = $this->sendToSwoftRpc( 'tcp://192.168.3.61:18307',\App\Rpc\Lib\UserInterface::class, 'getList',  [1, 2], "1.0");
`

**swoft 调用tp6+swoole think-swoole3.0的方法**
`
private function sendToTpsRpc($host, $interface, $method, $param) {
    $fp = stream_socket_client($host, $errno, $errstr);
    if (!$fp) {
        throw new Exception("stream_socket_client fail errno={$errno} errstr={$errstr}");
    }

    $req = [
        "jsonrpc" => '2.0',
        "method" => sprintf("%s@%s",$interface, $method),
        'params' => $param,
        'id' => '',
    ];
    $data = json_encode($req) . "\r\n\r\n";
    fwrite($fp, $data);

    $result = '';
    while (!feof($fp)) {
        $tmp = stream_socket_recvfrom($fp, 1024);

        if ($pos = strpos($tmp, "\r\n\r\n")) {
            $result .= substr($tmp, 0, $pos);
            break;
        } else {
            $result .= $tmp;
        }
    }

    fclose($fp);
    return json_decode($result, true);
}
//调用 Nanyounan这个是app\rpc\interfaces\Nanyounan 接口类
$ret = $this->sendToTpsRpc('tcp://192.168.3.61:9000', "Nanyounan", 'wuyujia',  ['1']);
`

**Comment by xavieryang007** [comment]
连接swoft的rpc需要用他的client
